import React from 'react';
import Head from 'next/head';
import { useTranslation } from 'next-i18next';
import { styled } from '@mui/material/styles';

import styles from './layout.module.scss';
import Navbar from '../navbar';
import Footer from './footer';

const StyledDiv = styled('div')(({ theme }) => ({
  backgroundColor: theme.palette.secondary.main,
  width: '100%',
}));

type Props = {
  children: JSX.Element;
};

const Layout = ({ children }: Props) => {
  const { t } = useTranslation('common');

  return (
    <div className={styles.container}>
      <Head>
        <title>Interstellar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <StyledDiv className={styles.main}>{children}</StyledDiv>
      <Footer />
    </div>
  );
};

export default Layout;
