import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useTranslation } from 'next-i18next';
import { styled } from '@mui/material/styles';
import styles from './layout.module.scss';
import { Navbar } from '../navbar';

const StyledDiv = styled('div')(({ theme }) => ({
  backgroundColor: theme.palette.secondary.main,
  width: '100%',
}));

const StyledFooter = styled('footer')(({ theme }) => ({}));

type Props = {
  children: JSX.Element;
};

const Layout = ({ children }: Props) => {
  const { t } = useTranslation('common');

  return (
    <div className={styles.container}>
      <Head>
        <title>Interstellar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <StyledDiv className={styles.main}>{children}</StyledDiv>
      <StyledFooter className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </StyledFooter>
    </div>
  );
};

export default Layout;
